# /home/siisi/super/siisi/siisi/docker-compose.yml

services:
  # --- Reverse Proxy & SSL ---
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - siisi-network
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginx-letsencrypt
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=medusadbt@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - siisi-network
    restart: always

  # --- Database ---
  db:
    image: postgres:latest
    container_name: siisi-db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - siisi-db-data:/var/lib/postgresql/data/pgdata
      - ./odoo_pg_pass:/run/secrets/postgresql_password:ro
    networks:
      - siisi-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  # --- Odoo Services ---
  siisi:
    image: odoo:latest
    container_name: siisi
    environment:
      - VIRTUAL_HOST=siisi.online,www.siisi.online
      - LETSENCRYPT_HOST=siisi.online,www.siisi.online
      - VIRTUAL_PORT=8069
      - VIRTUAL_PROTO=http
      - HOST=db
      - USER=odoo
      - PASSWORD_FILE=/run/secrets/postgresql_password
      - DB_NAME=siisi
      #- ADDONS_PATH=/mnt/extra-addons,/usr/lib/python3/site-packages/odoo/addons
      - ADDONS_PATH=/mnt/custom-addons,/mnt/oca-addons,/usr/lib/python3/site-packages/odoo/addons
    volumes:
      - siisi-data:/var/lib/odoo
      - ./config:/etc/odoo
      #- ./addons:/mnt/extra-addons
      #- ./logs:/var/log/
      - ./custom-addons:/mnt/custom-addons
      - ./oca-addons:/mnt/oca-addons
      - ./logs:/var/log/siisi/siisi/logs
      - ./odoo_pg_pass:/run/secrets/postgresql_password:ro
    networks:
      - siisi-network
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  siisi-db-data:
  siisi-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass

networks:
  siisi-network:
    driver: bridge
