# /home/siisi/super/odoo/scratch/docker-compose.yml

services:
  odoo_db_local:
    image: postgres:latest
    container_name: odoo-db-local
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data-local:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-network-local
    secrets:
      - postgresql_password
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  #odoo16_local:
  #  image: odoo:16.0
  #  container_name: odoo16-web-local
  #  environment:
  #    - VIRTUAL_PORT=8069
  #    - HOST=odoo-db-local
  #    - POSTGRES_USER=odoo
  #    - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
  #    - DB_NAME=odoo16_local
  #    #- ADDONS_PATH=/mnt/extra-addons,/usr/lib/python3/site-packages/odoo/addons
  #    - ADDONS_PATH=/mnt/custom-addons,/mnt/oca-addons,/usr/lib/python3/dist-packages/odoo/addons
  #  ports:
  #    - "8016:8069"
  #  volumes:
  #    - odoo16-web-data-local:/var/lib/odoo
  #    - ./config:/etc/odoo
  #    - ./custom-addons:/mnt/custom-addons
  #    - ./oca-addons:/mnt/oca-addons
  #    - ./logs:/var/log/odoo/scratch/logs
  #  networks:
  #    - odoo-network-local
  #  secrets:
  #    - postgresql_password
  #  restart: always
  #  depends_on:
  #    odoo_db_local:
  #      condition: service_healthy

  gestion_local:
    image: odoo:latest
    container_name: gestion-web-local
    environment:
      - VIRTUAL_PORT=8069
      - HOST=odoo-db-local
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - DB_NAME=gestion_local
      #- ADDONS_PATH=/mnt/extra-addons,/usr/lib/python3/site-packages/odoo/addons
      #- ADDONS_PATH=/mnt/custom-addons,/usr/lib/python3/site-packages/odoo/addons
      - ADDONS_PATH=/mnt/custom-addons,/mnt/oca-addons,/usr/lib/python3/site-packages/odoo/addons
    ports:
      - "8011:8069"
    volumes:
      - gestion-web-data-local:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/custom-addons
      - ./oca-addons:/mnt/oca-addons
      - ./logs:/var/log/siisi/scratch/logs
    networks:
      - odoo-network-local
    secrets:
      - postgresql_password
    restart: always
    depends_on:
      odoo_db_local:
        condition: service_healthy

volumes:
  odoo-db-data-local:
  #odoo16-web-data-local:
  gestion-web-data-local:

secrets:
  postgresql_password:
    file: odoo_pg_pass

networks:
  odoo-network-local:
    driver: bridge
